name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".vscode/**"
      - ".idea/**"

permissions:
  contents: read
  packages: read

jobs:
  ci-dapp:
    name: CI Dapp
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./src/dapp
      compile-script: npm run typecheck
  ci-api:
    name: CI API
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./src/voting-metadata-api
      compile-script: npm run typecheck
  ci-infrastructure:
    name: CI Infrastructure
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./infrastructure

  build-dapp:
    name: Build Dapp
    uses: ./.github/workflows/node-build-zip.yml
    with:
      working-directory: ./src/dapp
      build-path: dist
      artifact-name: dapp
      static-site: true
      static-site-env-prefix: VITE
    needs:
      - ci-dapp
  build-api:
    name: Build API
    uses: ./.github/workflows/node-build-zip.yml
    with:
      working-directory: ./src/voting-metadata-api
      artifact-name: api
    needs:
      - ci-api
  build-infrastructure:
    name: Build Infrastructure
    uses: ./.github/workflows/node-build-zip.yml
    with:
      working-directory: ./infrastructure
      artifact-name: infrastructure
    needs:
      - ci-infrastructure

  deploy-to-dev:
    runs-on: ubuntu-latest
    name: Deploy to TestNet
    environment: Dev
    concurrency: "${{ github.workflow }}-dev"
    needs:
      - build-dapp
      - build-infrastructure
      - build-api
    steps:
      - name: Deploy
        uses: makerxstudio/shared-config/.github/actions/node-deploy-cdk@main
        env:
          DEPLOYMENT_ENVIRONMENT: testnet
          CDK_DEFAULT_ACCOUNT: ${{ secrets.DEV_CDK_DEFAULT_ACCOUNT }}
          AWS_DEFAULT_REGION: us-west-2
          BASE_DOMAIN: voting.algorand.foundation
          WEBSITE_BUILD_PATH: ${{ github.workspace }}/dapp/dist
          API_BUILD_PATH: ${{ github.workspace }}/api/build
          WEB3_STORAGE_API_TOKEN: ""
        with:
          app-artifact-unzips: |
            dapp:dapp/dist
            api:api/build
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2
          static-site-transforms: |
            VITE_ALGOD_NODE_CONFIG_TOKEN=${{ secrets.ALGOD_NODE_CONFIG_TOKEN }}
            VITE_ALGOD_NODE_CONFIG_SERVER=${{ secrets.ALGOD_NODE_CONFIG_SERVER }}
            VITE_ALGOD_NOTE_CONFIG_PORT=${{ secrets.ALGOD_NODE_CONFIG_PORT }}
            VITE_ALGOD_NETWORK=${{ secrets.ALGOD_NETWORK }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    environment: Prod
    concurrency: "${{ github.workflow }}-prod"
    needs:
      - deploy-to-dev
    steps:
      - name: Deploy
        uses: makerxstudio/shared-config/.github/actions/node-deploy-cdk@main
        env:
          DEPLOYMENT_ENVIRONMENT: prod
          CDK_DEFAULT_ACCOUNT: ${{ secrets.PROD_CDK_DEFAULT_ACCOUNT }}
          AWS_DEFAULT_REGION: us-west-2
          BASE_DOMAIN: voting.algorand.foundation
          WEBSITE_BUILD_PATH: ${{ github.workspace }}/dapp/dist
          API_BUILD_PATH: ${{ github.workspace }}/api/build
          WEB3_STORAGE_API_TOKEN: ""
        with:
          app-artifact-unzips: |
            dapp:dapp/dist
            api:api/build
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2
          static-site-transforms: |
            VITE_ALGOD_NODE_CONFIG_TOKEN=${{ secrets.ALGOD_NODE_CONFIG_TOKEN }}
            VITE_ALGOD_NODE_CONFIG_SERVER=${{ secrets.ALGOD_NODE_CONFIG_SERVER }}
            VITE_ALGOD_NOTE_CONFIG_PORT=${{ secrets.ALGOD_NODE_CONFIG_PORT }}
            VITE_ALGOD_NETWORK=${{ secrets.ALGOD_NETWORK }}
